name: slither-analysis

# Controls when the workflow will run
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.MY_REPO_PAT }}

      - name: Set up Node
        uses: actions/setup-node@v2

      - name: Install Yarn
        run: npm install

      - name: Run Slither
        uses: crytic/slither-action@main
        with:
          target: './src'
          slither-config: '.slither.config.json'