name: slither-analysis

# Controls when the workflow will run
on:
  push:
  pull_request:
    branches: [ master, develop, release/* ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.MY_REPO_PAT }}

      - name: Set up Node
        uses: actions/setup-node@v2

      - name: Run Slither
        uses: crytic/slither-action@main
        id: slither
        continue-on-error: true
        with:
          target: './src'
          node-version: 16
          slither-config: '.slither.config.json'
          slither-args: '--checklist --markdown-root https://github.com/ORG/REPO/blob/COMMIT/ > output.md'

      - name: "Post to PR"
        uses: EliLillyCo/github-actions-post-to-pr@main
        with:
          github_token: ${{ secrets.MY_REPO_PAT }}
          post_to_pr_definition: |
            [
              {
                "message_file": "./output.md",
                "title": "Slither Analysis"
              }
            ]
