# This is a basic workflow to help you get started with Actions

name: slither-analysis

# Controls when the workflow will run
on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: crytic/slither-action@main
        with:
          target: 'src/'
          config-file: '.slither.config.json'
      
