name: slither-analysis

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master, develop, release/* ]
  push:
    branches: [ develop ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    outputs:
      markdown: '${{ steps.slither.outputs.markdown }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.MY_REPO_PAT }}

      - name: Set up Node
        uses: actions/setup-node@v2

      - name: Run Slither
        uses: astariaxyz/slither-action@main
        id: slither
        continue-on-error: true
        with:
          target: './src'
          node-version: 16
          slither-config: '.slither.config.json'
          slither-args: '--checklist'
          markdown: results.md
      - name: Checkout
        # uses: actions/checkout@v2
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: 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
          gist_url: https://gist.github.com/SantiagoGregory/4a2d82e7fc788d8696fe13a5106a67e4
          gist_title: astaria_slither.md
          gist_description: Hosted slither output logs
          github_file: results.md
      - name: "Post to PR"
        uses: EliLillyCo/github-actions-post-to-pr@main
        with:
          github_token: ${{ secrets.MY_REPO_PAT }}
          post_to_pr_definition: |
            [
              {
                "message_file": "${{ steps.slither.outputs.markdown }}",
                "title": "Slither Analysis"
              }
            ]
      
